spring.application.name=vehiclemanagerservice

# TODO: Credentials nicht in Git pushen!
#       Credentials ueber Secrets Management Tools verwalten und fuer local in secrets-application.properties packen, die in .gitignore liegt
# Add database connection properties
# Database connection properties
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=vehicle_manager
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL-Logging: alle abgesetzten Queries in der Konsole ausgeben
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Statistics: Anzahl der DB-Queries pro Session im Log ausgeben
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG
