CREATE SCHEMA IF NOT EXISTS vehicle_manager;

CREATE TABLE IF NOT EXISTS person (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(250) NOT NULL,
    last_name VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS vehicle_type (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(250) NOT NULL,
    type VARCHAR(50) NOT NULL,
    CONSTRAINT chk_vehicle_type_type
        CHECK (type IN ('PUBLIC_TRANSPORT', 'CARGO', 'SERVICE')),
    CONSTRAINT uq_vehicle_type_name_type UNIQUE (name, type),
    person_responsible BIGINT NOT NULL,
    CONSTRAINT fk_vehicle_type_person_id FOREIGN KEY (person_responsible) REFERENCES person(id)
    );
-- TODO: ggf. Index auf Type, da das Frontend vermutlich nach Type suchen wird

CREATE TABLE IF NOT EXISTS vehicle (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Index is automatically created for primary key
    name VARCHAR(255) NOT NULL,
    vehicle_type BIGINT NOT NULL,
    registration_date TIMESTAMP WITH TIME ZONE NOT NULL,
    weight INT NOT NULL,
    ready_for_service BOOLEAN NOT NULL DEFAULT FALSE,
    number_of_axes INT NOT NULL,
    max_speed INT NOT NULL,
    CONSTRAINT fk_vehicle_vehicle_type_id FOREIGN KEY (vehicle_type) REFERENCES vehicle_type(id)
    );
-- TODO: ggf. Index auf Name, da das Frontend vermutlich nach Namen suchen wird
